---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quenk.
--- DateTime: 05/06/2022 18:10
---
ragdollMode = false
Input.Register("Ragdoll", "Comma")
Input.Bind("Ragdoll", InputEvent.Pressed, function(player)
    local ply = Client.GetLocalPlayer()
    if ply then
        local char = ply:GetControlledCharacter()
        if char then
            if ragdollMode == false then
                Events.CallRemote("makeRagdoll",player)
                ragdollMode = true
            else
                Events.CallRemote("unRagdoll",player)
                ragdollMode = false
            end
        end
    end
end)
