---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by quenk.
--- DateTime: 05/06/2022 18:06
---

Events.Subscribe("makeRagdoll", function(player)
        local char = player:GetControlledCharacter()
        if char then
            char:SetRagdollMode(true)
            end
end)

Events.Subscribe("unRagdoll", function(player)
    local char = player:GetControlledCharacter()
    if char then
        char:SetRagdollMode(false)
    end
end)